id = 3
title = "Cyber Academy: OSINT & Social Engineering"
short = "OSINT/Social Engineering" 
date = "Wednesday 10/12 8:00PM-10:00PM PT"
description = """Ever want to learn how to (ethically) cyberstalk someone? How to prevent yourself from being cyberstalked? Come learn about using open source intelligence (OSINT) and social engineering to learn juicy secrets about your frenemies!
"""
link = "https://fb.me/e/1LPm9kiMv"
slides = ""
