
slug = "bring-me-a-rock"
title = "Bring Me a Rock"
author = "Caolinn"
value = 10
description = """During penguin coutship, one penguin will find the smoothest pebble to bring to another penguin as a gift. She will then place it in the nest and continue to build a pebble mound for little penguin eggs. I could not imagine a better gift-- can you pretty please find me a nice rock from this (pile)[penguin_rocks.txt]"""
tags = [ "scripting" ]
files = [ "penguin_rocks.txt" ]
flag = "flag{iLoVeTUx}"
enabled = true
