title = "ACM Cyber"
start = 2022-05-18T18:00:00-06:00
stop = 2022-05-25T18:00:00-06:00
home = """
# Who is ACM Cyber?
Our mission is to create a community in which both experts and beginners alike can grow in the field of cybersecurity skills and knowledge. We want to make cybersecurity simple and accessible for everyone.

Cybersecurity sounds hard. We get it. We hold workshops throughout each quarter geared towards novices and hobbyists curious about the world of cybersecurity, on topics such as forensics, web hacking, cryptography, and reverse engineering. We also hold Capture The Flag (CTF) competitions in which teams can participate collaboratively to solve cybersecurity challenges. All our events are open to anyone and everyone, even if you have no experience whatsoever.

# Join Us!
So how will these workshops work? Before anything else, join our [Discord](https://discord.gg/j9dgf2q). We'll be recording video sessions every week to teach and work through examples. And as always, there'll be more challenges for you to practice with here!

# Stay Updated!
## Newsletter
Want to learn more? Sign up for our newsletter! Each week, we send out a newsletter about upcoming Cyber events, interesting cybersecurity news, breakdown the steps to past security exploits, and write-ups about CTFs! [Sign up here!](http://eepurl.com/dITnQH)

## Stalk Us
Find us on Facebook at [UCLA ACM Cyber](https://www.facebook.com/groups/320869398280511)

Chat with us on [Discord](https://discord.gg/j9dgf2q)

Email us at uclacyber@gmail.com
"""
