id = 2
title = "Psi Beta Rho Interest Meeting"
short = "PBR Interest" 
date = "Thursday 10/6 6:00PM-8:00PM PT"
description = """Want to be a hacker? 💻Come join Psi Beta Rho, ACM Cyber's competitive CTF team! 🥳 CTFs or Capture-the-Flags are competitions where you solve cybersecurity problems to earn points. 💯 This is a great opportunity to add to your resume and build on the skills you have learned at Cyber Academy! 📄 😎We will be having an interest meeting on Thursday, October 6th from 6-8 pm. Location at the ACM Clubhouse (Boelter Hall 4685 + 4801). NO EXPERIENCE NECESSARY! All skill levels and experiences are welcome! We will be going through information about the Fall 2022 season and having a short social where we will do some challenges (so make sure to bring a laptop)! Be sure to invite your friends!
"""
link = "https://fb.me/e/5seYOjZ4u"
slides = ""
