id = 4
title = "Cyber Academy: Scripting & Linux Fundamentals"
short = "Python/Linux" 
date = "Wednesday 10/19 8:00PM-10:00PM PT"
description = """Want to emulate the hackers of mainstream tv with cool terminal-based shenanigans? Tired of manually carrying out long tasks?  Come out to Cyber’s scripting and linux fundamentals workshop to learn all about what you can do with a terminal, get into some basic bash and python, and build the foundation to become an elite hacker.
"""
link = "https://fb.me/e/30v9ALbMo"
slides = ""
